[package]
name = "scanner"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1"
chrono = "0.4.19"
clap = "3.0.0-beta.4"
rusqlite = { version = "0.26", features = [ "chrono" ] }
